import React, { useEffect, useRef, useState } from 'react';
import type { ChatMessage, DocumentMetadata } from '../types';

interface Props { document: DocumentMetadata; messages: ChatMessage[]; onSendMessage: (question: string) => Promise<void>; isLoading: boolean; onClearChat: () => void; onSelectSample?: (type: string) => void; }
export const ChatWorkspace: React.FC<Props> = ({ document, messages, onSendMessage, isLoading, onClearChat }) => {
  const [input, setInput] = useState('');
  const endRef = useRef<HTMLDivElement>(null);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages.length, isLoading]);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); const q = input.trim(); if (!q || isLoading) return; setInput(''); await onSendMessage(q); };
  return <div className="grid h-full min-h-0 grid-cols-1 gap-4 p-3 lg:grid-cols-[1fr_420px]">
    <section className="hidden min-h-0 rounded-xl border border-white/10 bg-[#141414] lg:flex lg:flex-col"><div className="border-b border-white/10 p-4"><p className="text-sm font-semibold text-white">{document.filename}</p><p className="mt-1 text-xs text-white/40">Document workspace</p></div><div className="flex flex-1 items-center justify-center text-center p-6"><div><div className="text-5xl">📄</div><p className="mt-3 text-sm text-white/55">PDF document loaded</p><p className="mt-1 text-xs text-white/30">Use the chat panel to interrogate the document.</p></div></div></section>
    <section className="flex min-h-0 flex-col overflow-hidden rounded-xl border border-white/10 bg-[#141414]"><div className="flex items-center justify-between border-b border-white/10 bg-[#0f0f0f] px-4 py-3"><div><p className="font-semibold text-white">Grounded chat</p><p className="text-[10px] uppercase tracking-wider text-[#C5A059]">Document-aware answers</p></div><button onClick={onClearChat} className="text-xs text-white/40 hover:text-white">Clear</button></div><div className="min-h-0 flex-1 overflow-y-auto p-4 space-y-3">{messages.length === 0 && <div className="rounded-lg border border-white/10 bg-black/20 p-4 text-xs leading-5 text-white/40">Ask a question about the uploaded PDF. Answers are generated from retrieved document context.</div>}{messages.map((m) => <article key={m.id} className={`rounded-xl p-3 ${m.role === 'user' ? 'ml-8 bg-[#222]' : 'mr-3 border border-white/10 bg-[#101010]'}`}><p className="text-[10px] uppercase tracking-wider text-white/35">{m.role === 'user' ? 'You' : 'Assistant'}</p><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-white/80">{m.content}</p>{m.role === 'assistant' && m.sources?.length > 0 && <div className="mt-3 space-y-2">{m.sources.map((s) => <div key={s.id} className="rounded border border-[#C5A059]/15 bg-[#C5A059]/5 p-2 text-xs text-white/55"><span className="text-[#DFBE7B]">Page {s.pageNumber}</span> · {s.excerpt}</div>)}</div>}</article>)}{isLoading && <div className="text-xs text-[#DFBE7B]">Generating grounded answer…</div>}<div ref={endRef}/></div><form onSubmit={submit} className="border-t border-white/10 p-3"><div className="flex gap-2"><input value={input} onChange={(e) => setInput(e.target.value)} placeholder="Ask a question about this PDF…" className="min-w-0 flex-1 rounded-lg border border-white/10 bg-black/20 px-3 py-2.5 text-sm text-white outline-none placeholder:text-white/25 focus:border-[#C5A059]/50"/><button disabled={isLoading || !input.trim()} className="rounded-lg bg-[#C5A059] px-4 py-2.5 text-sm font-semibold text-black disabled:opacity-40">Ask</button></div></form></section>
  </div>;
};
